### PR TITLE
Special ccache handling for {HOSTNAME} acceptor

### LINKED ISSUE #234: Multiple keys and delegation
Our Apache server hosts wsgi application (mod_wsgi) and uses mod_gssapi for authentication. moreover, the application uses delegation to pass the authenticated user to a backend service as follow:

`client request --> HTTP/apache_1@OUR_REALM --> HTTP/backend_server@OUR_REALM`

This works perfect, but now we need to add load balancer in front of the Apache server:

```
                                            -->  HTTP/apache_1@OUR_REALM --> HTTP/backend_server@OUR_REALM
client request -->  HTTP/balancer@OUR_REALM |  
                                            -->  HTTP/apache_2@OUR_REALM --> HTTP/backend_server@OUR_REALM
```

blancer server just forwards requests - no security configuration whatsoever and works as expected.

To make this work, we did the following:
 1. created new principal `HTTP/balancer@OUR_REALM` with constrained delegation to the backend service.
 2. Added the new principal to each of the existing keytabs of apache_1 and apache_2 servers:
 	**On server apache_1:**
```
		KVNO 	Principal
		---- 	-------------------
			1 	HTTP/apache_1@OUR_REALM
			1	HTTP/balancer@OUR_REALM
```

	**On server apache_2:**

```
		KVNO 	Principal
		---- 	-------------------
			1 	HTTP/apache_2@OUR_REALM
			1	HTTP/balancer@OUR_REALM
```

While testing our configuration we issued http requests to our balancer and got the following error in Apache's error log:
`GSSError:(('Unspecified GSS failure. Minor code may provide more information', 851968), ('Matching credential not found (filename: /var/run/httpd/krbcache/user_principal@OUR_REALM)', -1765328243))`

Investigating the user's ccache using `klist -c /var/run/httpd/krbcache/user_principal@OUR_REALM` showed (start and expiration columns are omitted):
```
# example from server apache_1
Ticket cache: FILE:/var/run/httpd/krbcache/user_principal@OUR_REALM
Default principal: user_principal@OUR_REALM

Service principal
HTTP/balancer@OUR_REALM

krbtgt/OUR_REALM@OUR_REALM
for client HTTP/apache_1@OUR_REALM
```

--> Its seems that even though we executed requests to the balancer, the delegation ticket was still issued to HTTP/apache_1@OUR_REALM (tgt for client `HTTP/apache_1@OUR_REALM`). Same behavior was occurred on requests that were forwarded to apache_2 server.

We tried to change the order of the principals inside the keytabs so `HTTP/balancer@OUR_REALM` will be the first principal:

**on apache_1:**
```
KVNO 	Principal
---- 	-------------------
	1	HTTP/balancer@OUR_REALM
	1 	HTTP/apache_1@OUR_REALM
```

**on apache_2:**
```
KVNO 	Principal
---- 	-------------------
	1	HTTP/balancer@OUR_REALM
	1 	HTTP/apache_2@OUR_REALM
```

And now we got the opposite: requests issued to the balancer server were succeeded while requests to the concrete servers apache_1 or apache_2 were failed. Obviously, this is better than before since we got a working balancer, but still - its preferable to make the concrete servers answering as well (balancer may fail, monitoring and more).

Is there a way making **both** principals work for each of our balancer servers?

Thanks.

### PR DESCRIPTION
**Pull request by simo5**
Quoting part of a commit message in this PR: 
    When using the {HOTNAME} acceptor the principal used in the server
    ccache can vary with each request. GSSAPI does not handle gracefully
    a request to resolve a ccache if there is already another credential
    under a different name.

Fixes #234

### CODE REVIEW

**Comment by simo5** [comment]
@frozencemetery I got confirmation that this solves the actual problem on #234, would be nice to review and merge.

File: src/mod_auth_gssapi.c [hunk 1]
```diff
@@ -221,12 +224,59 @@ static bool mag_acquire_creds(request_rec *req,
                            "gss_import_name() failed to import hostnname");
             return false;
         }
+
```
Comment (frozencemetery) [inline src/mod_auth_gssapi.c:227]: Spurious whitespace change.

File: src/mod_auth_gssapi.c [hunk 2]
```diff
@@ -221,12 +224,59 @@ static bool mag_acquire_creds(request_rec *req,
...
     }
 
 #ifdef HAVE_CRED_STORE
-    gss_const_key_value_set_t store = cfg->cred_store;
+    gss_const_key_value_set_t store = NULL;
+
+    /* When using multiple names we need to use individual separate
+     * ccaches for each principal or gss_acquire_cred() on the default
+     * ccache will fail when names don't match, this is needed only
+     * for the s4u2proxy case, where we try to acquire proxy credetials
```
Comment (frozencemetery) [inline src/mod_auth_gssapi.c:238]: "credentials", and period.

File: src/mod_auth_gssapi.c [hunk 3]
```diff
@@ -221,12 +224,59 @@ static bool mag_acquire_creds(request_rec *req,
...
+            gss_key_value_element_desc *el = &cfg->cred_store->elements[i];
+            s->elements[i].key = el->key;
+            if (strcmp(el->key, "ccache") == 0) {
+                s->elements[i].value = ccname;
+                add = false;
+            } else {
+                s->elements[i].value = el->value;
+            }
+        }
+        if (add == true) {
```
Comment (frozencemetery) [inline src/mod_auth_gssapi.c:270]: `if (add) {`

File: src/mod_auth_gssapi.c [hunk 4]
```diff
@@ -221,12 +224,59 @@ static bool mag_acquire_creds(request_rec *req,
...
+     * ccache will fail when names don't match, this is needed only
+     * for the s4u2proxy case, where we try to acquire proxy credetials
+     * The lucky thing is that in this case we require the use of a
+     * delegated creedntials directory, so we just use this directory
+     * to also hold permanent ccaches for individual acceptor names. */
+    if (cfg->acceptor_name_from_req && cfg->use_s4u2proxy &&
+        cfg->deleg_ccache_dir) {
+
+        gss_key_value_set_desc *s;
+        size_t i;
```
Comment (frozencemetery) [inline src/mod_auth_gssapi.c:246]: Move declaration into `for` loop since we're C99 :)

File: src/mod_auth_gssapi.c [hunk 5]
```diff
@@ -221,12 +224,59 @@ static bool mag_acquire_creds(request_rec *req,
...
         acceptor_name = cfg->acceptor_name;
     }
 
 #ifdef HAVE_CRED_STORE
-    gss_const_key_value_set_t store = cfg->cred_store;
+    gss_const_key_value_set_t store = NULL;
+
+    /* When using multiple names we need to use individual separate
+     * ccaches for each principal or gss_acquire_cred() on the default
+     * ccache will fail when names don't match, this is needed only
```
Comment (frozencemetery) [inline src/mod_auth_gssapi.c:237]: Comma splice - "this" should begin a new sentence.

File: tests/magtests.py [hunk 6]
```diff
@@ -691,26 +691,36 @@ def test_no_negotiate(testdir, testenv, logfile):
...
+        for (name, fail) in [(WRAP_HOSTNAME, False),
+                             (WRAP_ALIASNAME, False),
+                             (WRAP_FAILNAME, True)]:
+            res = subprocess.Popen(["tests/t_hostname_acceptor.py",
+                                    name, test_name],
+                                   stdout=logfile, stderr=logfile,
+                                   env=testenv, preexec_fn=os.setsid)
+            res.wait()
+            if fail:
+                if res.returncode == 0:
```
Comment (frozencemetery) [inline tests/magtests.py:717]: Collapse conditional - `if fail and res.returncode == 0:`.

File: tests/magtests.py [hunk 7]
```diff
@@ -691,26 +691,36 @@ def test_no_negotiate(testdir, testenv, logfile):
...
+                    failed = True
+            else:
```
Comment (frozencemetery) [inline tests/magtests.py:719]: Here too - `elif not fail and res.returncode != 0`

**Review by frozencemetery — CHANGES_REQUESTED** [review]
Typo in commit message - "HOTNAME".  :fire:

The rest is all nits - I'll clean it up in a moment.

File: src/mod_auth_gssapi.c (hunk 4 above)
Comment (simo5) [reply src/mod_auth_gssapi.c]: This is the start of a block, it's perfectly C99 fine.

**Comment by simo5** [comment]
Your changes look good to me
